version: "3.8"

services:
  main:
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
      - ./.docker/db/:/db/
    restart: unless-stopped
    command: python src/main.py
  web:
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
      - ./.docker/db/:/db/
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DOCKER_EXPOSE_PORT?8000}:8000"
  db:
    image: postgres:14.1
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7.0
    restart: unless-stopped
    volumes:
      - ./.docker/redis-data:/data
